name: Deploy to EC2
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          cd CICD_Docker
          docker build --no-cache -t minhtannguyenzz/nest-docker:latest .
          docker push minhtannguyenzz/nest-docker:latest
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
      - name: Deploy to EC2
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: 13.251.16.105
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST << 'EOF'
            mkdir -p ~/CICD_Docker
            cd ~/CICD_Docker
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker stop nest-container || true
            docker rm nest-container || true
            docker pull minhtannguyenzz/nest-docker:latest
            docker run -d --name nest-container -p 3000:3000 minhtannguyenzz/nest-docker:latest
          EOF
