name: Deploy to EC2
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: |
          cd CICD
          docker build --no-cache -t nest-docker:latest .
          docker save nest-docker:latest | gzip > nest-docker.tar.gz
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 400 key.pem
      - name: Copy code and image to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r . ubuntu@$EC2_HOST:/home/ubuntu/CICD
          scp -o StrictHostKeyChecking=no -i key.pem nest-docker.tar.gz ubuntu@$EC2_HOST:/home/ubuntu/CICD/
      - name: Deploy to EC2
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          EC2_HOST: 13.251.16.105
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_HOST << 'EOF'
            mkdir -p ~/CICD
            cd ~/CICD
            docker load -i nest-docker.tar.gz
            docker stop nest-container || true
            docker rm nest-container || true
            docker run -d --name nest-container -p 3000:3000 nest-docker:latest
          EOF
